from exceptions import Exception

class AutoindexError(Exception):
    pass
    
