from __future__ import division

from exceptions import Exception

class AutoindexError(Exception):
  pass
